In [1]:
import sys
import pennylane as qml
from pennylane import numpy as np
from QMLatomLoader import *
from tqdm import tqdm
from scipy.optimize import minimize

n_qubit=3

init_params=np.abs(np.random.random(n_qubit*2+1,requires_grad=True))
opt = qml.AdagradOptimizer(stepsize=0.5)
params=init_params
batch=64

def cost(para):
    param=np.abs(para)
    return paraoptim(batchs=batch,classic_parameter=param[1:].reshape((n_qubit,2)), weigthed=True,cutoff_radius=param[0])

In [5]:
epochs=1000
losslist=[]
for i in tqdm(range(epochs)):
    if i%10==0:
        
        params,loss=opt.step_and_cost(cost,params)
        print(loss)
        losslist.append(loss)
        p=np.array(losslist)
        print(p)
        print(params)
    
    else:
        params=opt.step(cost,params)
        params=np.abs(params)

  0%|          | 1/1000 [00:00<12:09,  1.37it/s]

0.9702781311411673
[0.97027813]
[[ 1.46564448 -0.35551488]
 [ 1.30182416  1.29833691]
 [ 1.32157528 -0.33345088]
 [-0.19084477  1.23403521]
 [ 1.21406897  1.35443342]
 [ 1.25315338 -0.26141346]]


  1%|          | 11/1000 [00:07<11:09,  1.48it/s]

0.6473332191038008
[0.97027813 0.64733322]
[[ 2.58231707  0.89969932]
 [ 3.26973219  3.26572971]
 [ 3.46778018 -0.07381551]
 [ 1.08125619  2.90869037]
 [ 3.37104737  3.45467092]
 [ 3.34039043 -0.09880759]]


  2%|▏         | 21/1000 [00:15<11:43,  1.39it/s]

0.5514795735435645
[0.97027813 0.64733322 0.55147957]
[[ 3.18590128  0.92891337]
 [ 3.97051417  4.13326038]
 [ 4.18194616 -0.02693295]
 [ 1.55479004  3.06739932]
 [ 4.22913134  4.53419939]
 [ 4.10633027 -0.02915691]]


  3%|▎         | 31/1000 [00:22<11:33,  1.40it/s]

0.5326425559703561
[0.97027813 0.64733322 0.55147957 0.53264256]
[[ 3.83337523  0.82781769]
 [ 4.44053887  4.65879076]
 [ 4.51430457 -0.01634788]
 [ 1.88244938  3.04849969]
 [ 4.7935487   5.16767606]
 [ 4.45310282 -0.01739966]]


  4%|▍         | 41/1000 [00:30<11:08,  1.44it/s]

0.5076289276410337
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893]
[[ 4.50070442  0.7909501 ]
 [ 4.78797373  4.95854205]
 [ 4.74266936 -0.01412269]
 [ 2.14742097  3.02258821]
 [ 5.15339286  5.56526088]
 [ 4.68835813 -0.0148217 ]]


  5%|▌         | 51/1000 [00:37<13:19,  1.19it/s]

0.49574295850647976
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296]
[[ 5.17653378  0.71459241]
 [ 5.06749325  5.40234672]
 [ 4.91704997 -0.0097105 ]
 [ 2.38109354  2.97174263]
 [ 5.38471182  5.76211671]
 [ 4.86694047 -0.01018401]]


  6%|▌         | 61/1000 [00:44<11:19,  1.38it/s]

0.49272830276247553
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283 ]
[[ 5.76760863  0.74783567]
 [ 5.26370939  5.6222655 ]
 [ 5.05970764 -0.00973067]
 [ 2.60200051  2.94015045]
 [ 5.57296839  5.90432803]
 [ 5.01237373 -0.01018536]]


  7%|▋         | 71/1000 [00:52<12:06,  1.28it/s]

0.4893791438201622
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914]
[[ 6.37218809  0.73087589]
 [ 5.4372309   5.78083081]
 [ 5.18068244 -0.01049956]
 [ 2.81067279  2.89332392]
 [ 5.73472969  6.01726674]
 [ 5.13537774 -0.01091127]]


  8%|▊         | 81/1000 [00:59<10:45,  1.42it/s]

0.47602614081044875
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614]
[[ 6.94108598e+00  7.23127455e-01]
 [ 5.57494919e+00  5.88087165e+00]
 [ 5.28413277e+00 -6.70529880e-03]
 [ 2.99649629e+00  2.85441490e+00]
 [ 5.85896730e+00  6.10010407e+00]
 [ 5.24035863e+00 -6.95443537e-03]]


  9%|▉         | 91/1000 [01:06<12:04,  1.25it/s]

0.4716497415519648
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974]
[[ 7.46088234e+00  7.24270171e-01]
 [ 5.69656537e+00  5.98725803e+00]
 [ 5.37588081e+00 -6.74557683e-03]
 [ 3.17533338e+00  2.86116262e+00]
 [ 5.97465349e+00  6.17958072e+00]
 [ 5.33330894e+00 -7.00811167e-03]]


 10%|█         | 101/1000 [01:13<10:24,  1.44it/s]

0.4790680851797259
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809]
[[ 7.93423217e+00  7.39568390e-01]
 [ 5.81418195e+00  6.08523119e+00]
 [ 5.46061897e+00 -5.94770727e-03]
 [ 3.35241613e+00  2.86331454e+00]
 [ 6.08486853e+00  6.25239174e+00]
 [ 5.41900813e+00 -6.14549207e-03]]


 11%|█         | 111/1000 [01:21<11:11,  1.32it/s]

0.4730828056542518
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281]
[[ 8.35151503e+00  7.41811530e-01]
 [ 5.92064357e+00  6.18071225e+00]
 [ 5.53597898e+00 -4.98078028e-03]
 [ 3.53188484e+00  2.80956004e+00]
 [ 6.18423480e+00  6.32416646e+00]
 [ 5.49516783e+00 -5.15932611e-03]]


 12%|█▏        | 121/1000 [01:28<10:06,  1.45it/s]

0.4639365354576691
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654]
[[ 8.73814559e+00  7.44085066e-01]
 [ 6.02969215e+00  6.26750251e+00]
 [ 5.60719336e+00 -5.96456407e-03]
 [ 3.68928028e+00  2.85475460e+00]
 [ 6.28176460e+00  6.38565576e+00]
 [ 5.56704818e+00 -6.14561872e-03]]


 13%|█▎        | 131/1000 [01:35<10:52,  1.33it/s]

0.4593758664383083
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587]
[[ 9.08190036e+00  7.53117905e-01]
 [ 6.12356691e+00  6.34037480e+00]
 [ 5.67139077e+00 -4.94379028e-03]
 [ 3.83628761e+00  2.82508504e+00]
 [ 6.36535476e+00  6.43838293e+00]
 [ 5.63182484e+00 -5.09119438e-03]]


 14%|█▍        | 141/1000 [01:42<09:39,  1.48it/s]

0.45282546760258935
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547]
[[ 9.38977987e+00  7.63619752e-01]
 [ 6.20258503e+00  6.40967062e+00]
 [ 5.73002548e+00 -4.48174259e-03]
 [ 3.99514547e+00  2.86197172e+00]
 [ 6.43748571e+00  6.48785505e+00]
 [ 5.69094367e+00 -4.63106974e-03]]


 15%|█▌        | 151/1000 [01:49<10:00,  1.41it/s]

0.46277927940276814
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928]
[[ 9.67661882e+00  7.41102524e-01]
 [ 6.28384673e+00  6.46914583e+00]
 [ 5.78617677e+00 -4.95064718e-03]
 [ 4.14083011e+00  2.81932910e+00]
 [ 6.51392237e+00  6.53589000e+00]
 [ 5.74751786e+00 -5.11023962e-03]]


 16%|█▌        | 161/1000 [01:56<10:12,  1.37it/s]

0.4532428762844305
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288]
[[ 9.94021729e+00  7.46688564e-01]
 [ 6.35975423e+00  6.51978518e+00]
 [ 5.83846168e+00 -4.94198817e-03]
 [ 4.28741270e+00  2.84721710e+00]
 [ 6.58356312e+00  6.57445799e+00]
 [ 5.80016882e+00 -5.09197122e-03]]


 17%|█▋        | 171/1000 [02:04<09:56,  1.39it/s]

0.44485581792669276
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582]
[[ 1.01722797e+01  7.57020451e-01]
 [ 6.41758262e+00  6.56867549e+00]
 [ 5.88777625e+00 -4.73785131e-03]
 [ 4.43239223e+00  2.76492715e+00]
 [ 6.63805669e+00  6.61234623e+00]
 [ 5.84981865e+00 -4.87056723e-03]]


 18%|█▊        | 181/1000 [02:11<09:47,  1.39it/s]

0.4548278513000177
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785]
[[ 1.03919355e+01  7.51597805e-01]
 [ 6.47604566e+00  6.61566866e+00]
 [ 5.93347945e+00 -6.34202016e-03]
 [ 4.57190949e+00  2.80126601e+00]
 [ 6.69283239e+00  6.64595571e+00]
 [ 5.89581617e+00 -6.48822050e-03]]


 19%|█▉        | 191/1000 [02:19<09:52,  1.36it/s]

0.44005839367560706
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839]
[[ 1.06018807e+01  7.65666076e-01]
 [ 6.53868671e+00  6.65844510e+00]
 [ 5.97739009e+00 -5.06585011e-03]
 [ 4.71357294e+00  2.85012361e+00]
 [ 6.74963398e+00  6.67694630e+00]
 [ 5.93998912e+00 -5.16569062e-03]]


 20%|██        | 201/1000 [02:26<09:37,  1.38it/s]

0.44712953799778754
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954]
[[ 1.07901965e+01  7.65971093e-01]
 [ 6.60875128e+00  6.71195365e+00]
 [ 6.01854345e+00 -4.00935915e-03]
 [ 4.84958726e+00  2.84103289e+00]
 [ 6.81171434e+00  6.71478567e+00]
 [ 5.98137474e+00 -4.09251930e-03]]


 21%|██        | 211/1000 [02:34<08:59,  1.46it/s]

0.4422060437026947
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604]
[[ 1.09714595e+01  7.63996466e-01]
 [ 6.66608586e+00  6.74917711e+00]
 [ 6.05783105e+00 -2.80356531e-03]
 [ 4.98916358e+00  2.88309002e+00]
 [ 6.86357260e+00  6.74144442e+00]
 [ 6.02087814e+00 -2.86705824e-03]]


 22%|██▏       | 221/1000 [02:41<10:25,  1.25it/s]

0.43760292164359743
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292]
[[ 1.11407632e+01  7.60687009e-01]
 [ 6.73287880e+00  6.79447490e+00]
 [ 6.09494295e+00 -2.94764016e-03]
 [ 5.11318798e+00  2.85527425e+00]
 [ 6.92273321e+00  6.77311888e+00]
 [ 6.05817941e+00 -3.04512328e-03]]


 23%|██▎       | 231/1000 [02:50<10:21,  1.24it/s]

0.44605254295689784
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254]
[[ 1.13002304e+01  7.62353417e-01]
 [ 6.78480574e+00  6.83174898e+00]
 [ 6.13158194e+00 -4.08426233e-03]
 [ 5.24315533e+00  2.82794772e+00]
 [ 6.96943036e+00  6.79882725e+00]
 [ 6.09499226e+00 -4.19934517e-03]]


 24%|██▍       | 241/1000 [02:58<12:18,  1.03it/s]

0.4342880925676623
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809]
[[ 1.14564904e+01  7.74211898e-01]
 [ 6.84268466e+00  6.86924907e+00]
 [ 6.16667951e+00 -2.84283026e-03]
 [ 5.36222032e+00  2.78977466e+00]
 [ 7.02106335e+00  6.82525775e+00]
 [ 6.13025499e+00 -2.91928828e-03]]


 25%|██▌       | 251/1000 [03:06<09:37,  1.30it/s]

0.43969159963027893
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916 ]
[[ 1.16049893e+01  7.56491410e-01]
 [ 6.90296744e+00  6.90926060e+00]
 [ 6.19870902e+00 -3.07963797e-03]
 [ 5.48422476e+00  2.88202258e+00]
 [ 7.07503280e+00  6.85310845e+00]
 [ 6.16243968e+00 -3.15165839e-03]]


 26%|██▌       | 261/1000 [03:14<11:20,  1.09it/s]

0.4420341938760987
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419]
[[ 1.17357057e+01  7.68784802e-01]
 [ 6.96044950e+00  6.94887769e+00]
 [ 6.23033127e+00 -3.32144579e-03]
 [ 5.60447448e+00  2.80793542e+00]
 [ 7.12644280e+00  6.88150475e+00]
 [ 6.19420373e+00 -3.40284645e-03]]


 27%|██▋       | 271/1000 [03:22<09:51,  1.23it/s]

0.44060960214559625
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096 ]
[[ 1.18643095e+01  7.55240663e-01]
 [ 7.01506939e+00  6.99002556e+00]
 [ 6.26116109e+00 -4.37681341e-03]
 [ 5.72461193e+00  2.81601167e+00]
 [ 7.17484188e+00  6.91108321e+00]
 [ 6.22516176e+00 -4.47351785e-03]]


 28%|██▊       | 281/1000 [03:31<10:39,  1.12it/s]

0.4486338567063542
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386]
[[ 1.19954659e+01  7.66306548e-01]
 [ 7.06478629e+00  7.02910935e+00]
 [ 6.29127129e+00 -2.77709840e-03]
 [ 5.84278829e+00  2.84058334e+00]
 [ 7.21898230e+00  6.93912369e+00]
 [ 6.25539208e+00 -2.83842092e-03]]


 29%|██▉       | 291/1000 [03:39<09:34,  1.23it/s]

0.4287283701704658
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837]
[[ 1.21168824e+01  7.60199582e-01]
 [ 7.11597600e+00  7.06337366e+00]
 [ 6.31950284e+00 -2.68260903e-03]
 [ 5.95747207e+00  2.78848243e+00]
 [ 7.26264210e+00  6.96118634e+00]
 [ 6.28374002e+00 -2.75081256e-03]]


 30%|███       | 301/1000 [03:47<09:49,  1.19it/s]

0.4426486581412246
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866]
[[ 1.22350664e+01  7.67730304e-01]
 [ 7.16167267e+00  7.10105032e+00]
 [ 6.34665846e+00 -1.82716854e-03]
 [ 6.06665055e+00  2.82812756e+00]
 [ 7.30341508e+00  6.98764968e+00]
 [ 6.31100119e+00 -1.88473386e-03]]


 31%|███       | 311/1000 [03:55<08:21,  1.37it/s]

0.43745520229397244
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552 ]
[[ 1.23507578e+01  7.64807018e-01]
 [ 7.20696861e+00  7.13084583e+00]
 [ 6.37303543e+00 -2.24360115e-03]
 [ 6.17887674e+00  2.83702559e+00]
 [ 7.34449471e+00  7.00829898e+00]
 [ 6.33748002e+00 -2.31502612e-03]]


 32%|███▏      | 321/1000 [04:02<08:20,  1.36it/s]

0.43408119632434966
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812 ]
[[ 1.24616717e+01  7.49296594e-01]
 [ 7.24453966e+00  7.15787705e+00]
 [ 6.39887210e+00 -1.70966406e-03]
 [ 6.29123900e+00  2.87293298e+00]
 [ 7.37725244e+00  7.02695501e+00]
 [ 6.36341275e+00 -1.76677379e-03]]


 33%|███▎      | 331/1000 [04:09<07:33,  1.47it/s]

0.43169833440557204
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833]
[[ 1.25702927e+01  7.64736668e-01]
 [ 7.28577259e+00  7.18828992e+00]
 [ 6.42345385e+00 -2.39605797e-03]
 [ 6.39642249e+00  2.84752650e+00]
 [ 7.41358504e+00  7.04871470e+00]
 [ 6.38807890e+00 -2.46949845e-03]]


 34%|███▍      | 341/1000 [04:16<07:40,  1.43it/s]

0.437814216212648
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422]
[[ 1.26734675e+01  7.62834186e-01]
 [ 7.32858402e+00  7.21253579e+00]
 [ 6.44834681e+00 -2.54221232e-03]
 [ 6.49805547e+00  2.77327175e+00]
 [ 7.45147100e+00  7.06499001e+00]
 [ 6.41305191e+00 -2.60617813e-03]]


 35%|███▌      | 351/1000 [04:23<07:34,  1.43it/s]

0.4327492909202982
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929]
[[ 1.27737500e+01  7.64502092e-01]
 [ 7.37052317e+00  7.24031272e+00]
 [ 6.47241648e+00 -1.89134176e-03]
 [ 6.60491473e+00  2.81549164e+00]
 [ 7.48878709e+00  7.08358807e+00]
 [ 6.43719857e+00 -1.94108404e-03]]


 36%|███▌      | 361/1000 [04:30<07:33,  1.41it/s]

0.4366416719814027
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167]
[[ 1.28699166e+01  7.66009539e-01]
 [ 7.41115977e+00  7.26742441e+00]
 [ 6.49574057e+00 -2.16444964e-03]
 [ 6.71264903e+00  2.78142196e+00]
 [ 7.52453341e+00  7.10345063e+00]
 [ 6.46059543e+00 -2.22333851e-03]]


 37%|███▋      | 371/1000 [04:37<07:26,  1.41it/s]

0.4425060303700315
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603]
[[ 1.29651820e+01  7.66073913e-01]
 [ 7.45274766e+00  7.29596191e+00]
 [ 6.51839168e+00 -2.53532929e-03]
 [ 6.81768378e+00  2.90811826e+00]
 [ 7.56111405e+00  7.12327996e+00]
 [ 6.48331429e+00 -2.59955821e-03]]


 38%|███▊      | 381/1000 [04:45<07:08,  1.44it/s]

0.4340622508315548
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225]
[[ 1.30550581e+01  7.57156609e-01]
 [ 7.49300526e+00  7.32179535e+00]
 [ 6.54037392e+00 -1.91127328e-03]
 [ 6.91360337e+00  2.80641704e+00]
 [ 7.59604626e+00  7.14421989e+00]
 [ 6.50535976e+00 -1.96515734e-03]]


 39%|███▉      | 391/1000 [04:52<06:57,  1.46it/s]

0.43688553273551367
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553]
[[ 1.31477743e+01  7.40667103e-01]
 [ 7.53733401e+00  7.35165931e+00]
 [ 6.56211033e+00 -1.58066674e-03]
 [ 7.01376440e+00  2.81474903e+00]
 [ 7.63283880e+00  7.16346240e+00]
 [ 6.52715733e+00 -1.62717237e-03]]


 40%|████      | 401/1000 [04:59<06:40,  1.50it/s]

0.43181000034310396
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181   ]
[[ 1.32317437e+01  7.66397744e-01]
 [ 7.57570586e+00  7.37483250e+00]
 [ 6.58304536e+00 -1.10493904e-03]
 [ 7.11097029e+00  2.79608184e+00]
 [ 7.66691473e+00  7.17956597e+00]
 [ 6.54814884e+00 -1.15223339e-03]]


 41%|████      | 411/1000 [05:06<06:36,  1.49it/s]

0.4328871031121523
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871 ]
[[ 1.33161195e+01  7.59938951e-01]
 [ 7.61245700e+00  7.39695686e+00]
 [ 6.60409514e+00 -1.36327066e-03]
 [ 7.20870601e+00  2.83047289e+00]
 [ 7.70085280e+00  7.18338140e+00]
 [ 6.56925223e+00 -1.41925749e-03]]


 42%|████▏     | 421/1000 [05:13<06:46,  1.42it/s]

0.43124945070426335
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945]
[[ 1.34009981e+01  7.65824326e-01]
 [ 7.64902346e+00  7.41610067e+00]
 [ 6.62415414e+00 -7.06185146e-04]
 [ 7.30155595e+00  2.77589611e+00]
 [ 7.73276201e+00  7.19532441e+00]
 [ 6.58936322e+00 -7.45067181e-04]]


 43%|████▎     | 431/1000 [05:21<08:05,  1.17it/s]

0.4268643719135807
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437]
[[ 1.34818351e+01  7.56340893e-01]
 [ 7.68784575e+00  7.43889920e+00]
 [ 6.64381335e+00 -1.03832209e-03]
 [ 7.39581096e+00  2.81198524e+00]
 [ 7.76636321e+00  7.21424112e+00]
 [ 6.60907334e+00 -1.08921185e-03]]


 44%|████▍     | 441/1000 [05:28<06:34,  1.42it/s]

0.4323243861512111
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439]
[[ 1.35624683e+01  7.59137392e-01]
 [ 7.72782283e+00  7.46051448e+00]
 [ 6.66323764e+00 -1.32635512e-03]
 [ 7.49150942e+00  2.81490719e+00]
 [ 7.80228896e+00  7.22996812e+00]
 [ 6.62854397e+00 -1.38477592e-03]]


 45%|████▌     | 451/1000 [05:35<07:24,  1.24it/s]

0.4314811526988931
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115]
[[ 1.36398990e+01  7.67889373e-01]
 [ 7.76140625e+00  7.47759063e+00]
 [ 6.68196938e+00 -1.22032982e-03]
 [ 7.58338205e+00  2.77118078e+00]
 [ 7.83164822e+00  7.24223940e+00]
 [ 6.64732192e+00 -1.27182767e-03]]


 46%|████▌     | 461/1000 [05:42<06:19,  1.42it/s]

0.4283232888106806
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329]
[[ 1.37195683e+01  7.74187334e-01]
 [ 7.79692425e+00  7.49745659e+00]
 [ 6.70054490e+00 -1.23714765e-03]
 [ 7.67281050e+00  2.78086717e+00]
 [ 7.86371709e+00  7.25617550e+00]
 [ 6.66593890e+00 -1.28576805e-03]]


 47%|████▋     | 471/1000 [05:50<06:54,  1.28it/s]

0.4296286333724872
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863]
[[ 1.37934365e+01  7.66884987e-01]
 [ 7.82685029e+00  7.51668648e+00]
 [ 6.71819236e+00 -1.66815701e-03]
 [ 7.76456344e+00  2.77503922e+00]
 [ 7.88843394e+00  7.26845164e+00]
 [ 6.68362909e+00 -1.72200847e-03]]


 48%|████▊     | 481/1000 [05:57<06:21,  1.36it/s]

0.4317120730066716
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207]
[[ 1.38696524e+01  7.68055991e-01]
 [ 7.86140427e+00  7.53410500e+00]
 [ 6.73606905e+00 -2.10104856e-03]
 [ 7.85591548e+00  2.83620312e+00]
 [ 7.92044148e+00  7.28311720e+00]
 [ 6.70154633e+00 -2.16024618e-03]]


 49%|████▉     | 491/1000 [06:05<06:29,  1.31it/s]

0.4354008157001621
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082]
[[ 1.39400401e+01  7.61711828e-01]
 [ 7.89606188e+00  7.55364508e+00]
 [ 6.75370695e+00 -2.22978218e-03]
 [ 7.94491575e+00  2.75102973e+00]
 [ 7.94654041e+00  7.29426738e+00]
 [ 6.71921850e+00 -2.28427044e-03]]


 50%|█████     | 501/1000 [06:12<06:07,  1.36it/s]

0.43598696223004213
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696]
[[ 1.40107508e+01  7.63131735e-01]
 [ 7.92811644e+00  7.57210692e+00]
 [ 6.77040417e+00 -2.08464197e-03]
 [ 8.03559983e+00  2.81558293e+00]
 [ 7.97590886e+00  7.30938069e+00]
 [ 6.73595311e+00 -2.13390235e-03]]


 51%|█████     | 511/1000 [06:20<06:24,  1.27it/s]

0.43516526838211783
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527]
[[ 1.40797508e+01  7.60073764e-01]
 [ 7.95927253e+00  7.59233514e+00]
 [ 6.78730048e+00 -2.03461206e-03]
 [ 8.12329458e+00  2.80469106e+00]
 [ 8.00326481e+00  7.32264881e+00]
 [ 6.75288296e+00 -2.08622159e-03]]


 52%|█████▏    | 521/1000 [06:27<06:04,  1.31it/s]

0.43071709888148746
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171 ]
[[ 1.41461251e+01  7.68272551e-01]
 [ 7.99041489e+00  7.61163368e+00]
 [ 6.80332264e+00 -1.67021953e-03]
 [ 8.20817623e+00  2.82876811e+00]
 [ 8.03202198e+00  7.33547342e+00]
 [ 6.76893750e+00 -1.71086855e-03]]


 53%|█████▎    | 531/1000 [06:35<05:31,  1.42it/s]

0.4345589951323806
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559  ]
[[ 1.42092388e+01  7.71214528e-01]
 [ 8.02321628e+00  7.63095350e+00]
 [ 6.81970051e+00 -2.07467830e-03]
 [ 8.29293929e+00  2.77964918e+00]
 [ 8.06182621e+00  7.34939979e+00]
 [ 6.78534533e+00 -2.12463454e-03]]


 54%|█████▍    | 541/1000 [06:42<05:30,  1.39it/s]

0.4386977292596133
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773]
[[ 1.42733441e+01  7.64777835e-01]
 [ 8.05820113e+00  7.65092301e+00]
 [ 6.83502129e+00 -1.70730542e-03]
 [ 8.37549264e+00  2.79629219e+00]
 [ 8.09355464e+00  7.36566069e+00]
 [ 6.80069911e+00 -1.74779714e-03]]


 55%|█████▌    | 551/1000 [06:50<05:38,  1.33it/s]

0.43023911290795175
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911]
[[ 1.43349278e+01  7.62206209e-01]
 [ 8.09084949e+00  7.66942175e+00]
 [ 6.85032645e+00 -1.23147618e-03]
 [ 8.45645399e+00  2.81174436e+00]
 [ 8.12293084e+00  7.37974951e+00]
 [ 6.81603320e+00 -1.26414906e-03]]


 56%|█████▌    | 561/1000 [06:57<05:12,  1.41it/s]

0.43577563991277074
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564]
[[ 1.43970519e+01  7.59407184e-01]
 [ 8.12020433e+00  7.68271873e+00]
 [ 6.86550985e+00 -8.12985482e-04]
 [ 8.54287878e+00  2.82075542e+00]
 [ 8.15031931e+00  7.39106376e+00]
 [ 6.83124353e+00 -8.41754264e-04]]


 57%|█████▋    | 571/1000 [07:04<05:07,  1.40it/s]

0.43520266658110573
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267]
[[ 1.44592081e+01  7.59376317e-01]
 [ 8.14884100e+00  7.70036551e+00]
 [ 6.88056113e+00 -1.02923524e-03]
 [ 8.62234262e+00  2.78156863e+00]
 [ 8.17468951e+00  7.40218790e+00]
 [ 6.84632348e+00 -1.06532539e-03]]


 58%|█████▊    | 581/1000 [07:11<04:35,  1.52it/s]

0.43115929136672665
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929]
[[ 1.45220988e+01  7.59485430e-01]
 [ 8.18215189e+00  7.72115918e+00]
 [ 6.89562556e+00 -1.11622695e-03]
 [ 8.70427872e+00  2.77931631e+00]
 [ 8.20409778e+00  7.41560941e+00]
 [ 6.86141257e+00 -1.15326515e-03]]


 59%|█████▉    | 591/1000 [07:19<05:03,  1.35it/s]

0.4278147920535409
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479]
[[ 1.45810531e+01  7.70781479e-01]
 [ 8.21163219e+00  7.73742270e+00]
 [ 6.90989189e+00 -1.52710134e-03]
 [ 8.78335836e+00  2.81377397e+00]
 [ 8.23050603e+00  7.42863606e+00]
 [ 6.87570479e+00 -1.57258319e-03]]


 60%|██████    | 601/1000 [07:26<04:29,  1.48it/s]

0.43239050398613654
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905 ]
[[ 1.46411246e+01  7.62097572e-01]
 [ 8.23995782e+00  7.75181819e+00]
 [ 6.92392568e+00 -1.15185033e-03]
 [ 8.86482804e+00  2.81680854e+00]
 [ 8.25716129e+00  7.44090050e+00]
 [ 6.88976276e+00 -1.18948982e-03]]


 61%|██████    | 611/1000 [07:33<04:44,  1.37it/s]

0.42296031376704674
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031]
[[ 1.46986547e+01  7.63726802e-01]
 [ 8.27065115e+00  7.76880226e+00]
 [ 6.93828805e+00 -1.49353626e-03]
 [ 8.94712772e+00  2.77477217e+00]
 [ 8.28423387e+00  7.45221729e+00]
 [ 6.90414575e+00 -1.53808107e-03]]


 62%|██████▏   | 621/1000 [07:41<05:41,  1.11it/s]

0.4195078394714527
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784]
[[ 1.47567340e+01  7.56633109e-01]
 [ 8.29578892e+00  7.78224322e+00]
 [ 6.95202513e+00 -1.03804214e-03]
 [ 9.02495456e+00  2.76304425e+00]
 [ 8.30619407e+00  7.46281183e+00]
 [ 6.91790446e+00 -1.07258489e-03]]


 63%|██████▎   | 631/1000 [07:48<04:26,  1.38it/s]

0.43075285306273164
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285]
[[ 1.48112596e+01  7.68381866e-01]
 [ 8.32414846e+00  7.79870292e+00]
 [ 6.96518532e+00 -7.70843554e-04]
 [ 9.10095491e+00  2.79021615e+00]
 [ 8.32930469e+00  7.47211936e+00]
 [ 6.93108769e+00 -8.02584065e-04]]


 64%|██████▍   | 641/1000 [07:56<05:08,  1.17it/s]

0.43232147003071353
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147]
[[ 1.48677076e+01  7.63393020e-01]
 [ 8.35291819e+00  7.81439390e+00]
 [ 6.97844962e+00 -1.28619616e-03]
 [ 9.17435417e+00  2.76915318e+00]
 [ 8.35438147e+00  7.48400534e+00]
 [ 6.94437373e+00 -1.32765635e-03]]


 65%|██████▌   | 651/1000 [08:03<04:05,  1.42it/s]

0.44197372418327885
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372]
[[ 1.49234638e+01  7.75832516e-01]
 [ 8.37880321e+00  7.82922371e+00]
 [ 6.99166752e+00 -1.21293101e-03]
 [ 9.25133543e+00  2.78768495e+00]
 [ 8.37745143e+00  7.49273782e+00]
 [ 6.95761086e+00 -1.24881489e-03]]


 66%|██████▌   | 661/1000 [08:10<04:17,  1.32it/s]

0.41845250757593666
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251]
[[ 1.49759690e+01  7.66068931e-01]
 [ 8.40381606e+00  7.84274178e+00]
 [ 7.00454271e+00 -1.21461767e-03]
 [ 9.32549053e+00  2.80658086e+00]
 [ 8.40027999e+00  7.50171058e+00]
 [ 6.97050503e+00 -1.24847917e-03]]


 67%|██████▋   | 671/1000 [08:18<03:54,  1.40it/s]

0.4306290828565902
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908]
[[ 1.50298741e+01  7.75158731e-01]
 [ 8.42935959e+00  7.85667356e+00]
 [ 7.01728556e+00 -1.33030321e-03]
 [ 9.39673179e+00  2.80865733e+00]
 [ 8.42349220e+00  7.51375821e+00]
 [ 6.98326762e+00 -1.36570717e-03]]


 68%|██████▊   | 681/1000 [08:25<03:57,  1.34it/s]

0.4156860224803373
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602]
[[ 1.50833360e+01  7.58309692e-01]
 [ 8.45865103e+00  7.87473941e+00]
 [ 7.02987629e+00 -1.83253915e-03]
 [ 9.46946254e+00  2.81151288e+00]
 [ 8.44952549e+00  7.52334119e+00]
 [ 6.99587542e+00 -1.87474816e-03]]


 69%|██████▉   | 691/1000 [08:32<03:33,  1.45it/s]

0.4239948004028193
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948 ]
[[ 1.51343400e+01  7.70014738e-01]
 [ 8.48427994e+00  7.89091836e+00]
 [ 7.04176403e+00 -9.55793295e-04]
 [ 9.54260324e+00  2.80208195e+00]
 [ 8.47272331e+00  7.53307559e+00]
 [ 7.00778382e+00 -9.78853

 70%|███████   | 701/1000 [08:39<03:35,  1.38it/s]

0.42965629787567927
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563 ]
[[ 1.51834937e+01  7.63714830e-01]
 [ 8.50722584e+00  7.90119673e+00]
 [ 7.05392244e+00 -1.71848756e-03]
 [ 9.61449875e+00  2.79146715e+00]
 [ 8.49406720e+00  7.54045045e+00]
 [ 7.01995945e

 71%|███████   | 711/1000 [08:46<03:24,  1.41it/s]

0.43280692892926503
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693]
[[ 1.52372617e+01  7.60941995e-01]
 [ 8.53347767e+00  7.91750009e+00]
 [ 7.06585220e+00 -2.63884705e-03]
 [ 9.68597339e+00  2.77470210e+00]
 [ 8.51879517e+00  7.55277261e+00]
 [ 

 72%|███████▏  | 721/1000 [08:54<03:17,  1.41it/s]

0.4283535098848559
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351]
[[ 1.52872478e+01  7.64186433e-01]
 [ 8.56287556e+00  7.93162233e+00]
 [ 7.07756327e+00 -1.94554789e-03]
 [ 9.75861815e+00  2.77682947e+00]
 [ 8.54408727e+00  7.563082

 73%|███████▎  | 731/1000 [09:00<02:50,  1.58it/s]

0.42398022834519833
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023]
[[ 1.53403331e+01  7.61979865e-01]
 [ 8.58807359e+00  7.94557529e+00]
 [ 7.08956568e+00 -1.49208118e-03]
 [ 9.83014021e+00  2.79610933e+00]
 [ 8.56698608e+

 74%|███████▍  | 741/1000 [09:07<02:42,  1.60it/s]

0.4260837858549192
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379]
[[ 1.53903966e+01  7.57734709e-01]
 [ 8.60974982e+00  7.95733385e+00]
 [ 7.10115118e+00 -1.70054612e-03]
 [ 9.90117089e+00  2.75100205e+00]
 [ 8.

 75%|███████▌  | 751/1000 [09:13<02:36,  1.59it/s]

0.4241605793930797
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058]
[[ 1.54394943e+01  7.66437383e-01]
 [ 8.63391138e+00  7.96938231e+00]
 [ 7.11239359e+00 -1.52858751e-03]
 [ 9.97174233e+00  2.78869207

 76%|███████▌  | 761/1000 [09:20<02:27,  1.62it/s]

0.4253236787128101
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368]
[[ 1.54882507e+01  7.61352477e-01]
 [ 8.65338355e+00  7.97967391e+00]
 [ 7.12353789e+00 -1.10017448e-03]
 [ 1.00382934e+01 

 77%|███████▋  | 771/1000 [09:26<02:20,  1.63it/s]

0.4385235659427317
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357]
[[ 1.55365614e+01  7.67258148e-01]
 [ 8.67936563e+00  7.99360574e+00]
 [ 7.13468659e+00 -9.35299805e-04]
 [ 1.01

 78%|███████▊  | 781/1000 [09:33<02:20,  1.56it/s]

0.42569339172117154
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339]
[[ 1.55858045e+01  7.66943913e-01]
 [ 8.70602692e+00  8.00731067e+00]
 [ 7.14570407e+00 -9.97005509

 79%|███████▉  | 791/1000 [09:39<02:11,  1.59it/s]

0.4314429821316487
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298]
[[ 1.56308920e+01  7.63919992e-01]
 [ 8.73178962e+00  8.02338374e+00]
 [ 7.15650544e+00 -

 80%|████████  | 801/1000 [09:46<02:05,  1.58it/s]

0.4331477337396574
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773]
[[ 1.56763566e+01  7.62494474e-01]
 [ 8.75440393e+00  8.03791681e+00]
 [ 7.167

 81%|████████  | 811/1000 [09:53<02:29,  1.26it/s]

0.4233890419410321
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904]
[[ 1.57217412e+01  7.63211542e-01]
 [ 8.77525912e+00  8.05122146e+0

 82%|████████▏ | 821/1000 [09:59<01:48,  1.66it/s]

0.434095946023842
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595]
[[ 1.57639166e+01  7.68236672e-01]
 [ 8.80739010e+00  8.0

 83%|████████▎ | 831/1000 [10:06<02:03,  1.37it/s]

0.4189743242714214
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432]
[[ 1.58079121e+01  7.63699258e-01]
 [ 8.82976

 84%|████████▍ | 841/1000 [10:12<01:47,  1.47it/s]

0.42367911440688955
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911]
[[ 1.58516006e+01  7.67584467e-0

 85%|████████▌ | 851/1000 [10:19<01:41,  1.47it/s]

0.4299599356768288
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994]
[[ 1.58983458e+01  7.6

 86%|████████▌ | 861/1000 [10:25<01:24,  1.65it/s]

0.42934066487132
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066]
[[ 1.59423376

 87%|████████▋ | 871/1000 [10:32<01:27,  1.47it/s]

0.4287020760264121
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208]


 88%|████████▊ | 881/1000 [10:38<01:13,  1.61it/s]

0.41790523122118023
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 

 89%|████████▉ | 891/1000 [10:45<01:11,  1.52it/s]

0.43400094494539726
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 

 90%|█████████ | 901/1000 [10:51<00:59,  1.66it/s]

0.4283336272883019
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 91%|█████████ | 911/1000 [10:57<00:57,  1.56it/s]

0.4254662017623481
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 92%|█████████▏| 921/1000 [11:03<00:46,  1.71it/s]

0.42404667480295555
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 

 93%|█████████▎| 931/1000 [11:10<00:44,  1.56it/s]

0.4250001010247196
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 94%|█████████▍| 941/1000 [11:16<00:36,  1.61it/s]

0.4229062381914624
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 95%|█████████▌| 951/1000 [11:23<00:30,  1.59it/s]

0.42409187958445027
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 

 96%|█████████▌| 961/1000 [11:29<00:23,  1.66it/s]

0.4249601555025614
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 97%|█████████▋| 971/1000 [11:36<00:18,  1.58it/s]

0.4218278951970392
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 98%|█████████▊| 981/1000 [11:42<00:11,  1.62it/s]

0.4242838747054465
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 0

 99%|█████████▉| 991/1000 [11:49<00:05,  1.60it/s]

0.42302432449163146
[0.97027813 0.64733322 0.55147957 0.53264256 0.50762893 0.49574296
 0.4927283  0.48937914 0.47602614 0.47164974 0.47906809 0.47308281
 0.46393654 0.45937587 0.45282547 0.46277928 0.45324288 0.44485582
 0.45482785 0.44005839 0.44712954 0.44220604 0.43760292 0.44605254
 0.43428809 0.4396916  0.44203419 0.4406096  0.44863386 0.42872837
 0.44264866 0.4374552  0.4340812  0.43169833 0.43781422 0.43274929
 0.43664167 0.44250603 0.43406225 0.43688553 0.43181    0.4328871
 0.43124945 0.42686437 0.43232439 0.43148115 0.42832329 0.42962863
 0.43171207 0.43540082 0.43598696 0.43516527 0.4307171  0.434559
 0.43869773 0.43023911 0.43577564 0.43520267 0.43115929 0.42781479
 0.4323905  0.42296031 0.41950784 0.43075285 0.43232147 0.44197372
 0.41845251 0.43062908 0.41568602 0.4239948  0.4296563  0.43280693
 0.42835351 0.42398023 0.42608379 0.42416058 0.42532368 0.43852357
 0.42569339 0.43144298 0.43314773 0.42338904 0.43409595 0.41897432
 0.42367911 0.42995994 0.42934066 0.42870208 

100%|██████████| 1000/1000 [11:54<00:00,  1.40it/s]


In [3]:
params

tensor([[7.44546256e+00, 3.58156079e-04],
        [1.61157272e+01, 7.72828926e-01],
        [5.79686532e+00, 8.85346477e+00]], requires_grad=True)

In [ ]:
np.array([[1.59032559e-03, 8.52561599e-01],
        [1.10705199e+00, 5.26487130e+00],
        [8.43135999e-01, 4.46610443e+00]], requires_grad=True)