In [145]:
t=torch.tensor([[1.9049e+04+0.j],
        [1.2365e+04+0.j],
        [1.2546e+01+0.j]])

In [158]:
def fun():
    return 1

In [169]:
a= torch.tensor([0.3377])

In [172]:
a[0].item()

0.3377000093460083

In [173]:
t2 = torch.tensor([[1,2],[3,4],[5,6]])

In [174]:
t2[1,1]

tensor(4)

In [115]:
H =7892.680830835166 * I^I^I+16949.519248246484 * X^I^I

In [153]:
coeff = np.array([1,2,3])

In [154]:
coeff2 = np.array([4,5,6])

In [155]:
coeff*coeff2

array([ 4, 10, 18])

In [119]:
torch.tensor(list(np.random.random(n_qubit*4)), requires_grad = True)

tensor([0.1881, 0.2749, 0.9560, 0.7990, 0.1730, 0.1286, 0.4245, 0.5080, 0.2555,
        0.1952, 0.9521, 0.3229, 0.8766, 0.0683, 0.3046, 0.5420, 0.8945, 0.6117,
        0.9852, 0.2632], dtype=torch.float64, requires_grad=True)

In [125]:
torch.rand(2, requires_grad=True)

tensor([0.3961, 0.0817], requires_grad=True)

In [109]:
psi = QuantumCircuit(n_qubit)
for i in range(n_qubit):
    psi.rz(-0.23,i)
    psi.ry(0.3,i)
    psi.rz(0.2,i)

In [118]:
CircuitStateFn(psi).adjoint().compose(H).compose(psi)

TypeError: ListOp expecting objects of type OperatorBase, got      ┌───────────┐┌─────────┐┌─────────┐
q_0: ┤ Rz(-0.23) ├┤ Ry(0.3) ├┤ Rz(0.2) ├
     ├───────────┤├─────────┤├─────────┤
q_1: ┤ Rz(-0.23) ├┤ Ry(0.3) ├┤ Rz(0.2) ├
     ├───────────┤├─────────┤├─────────┤
q_2: ┤ Rz(-0.23) ├┤ Ry(0.3) ├┤ Rz(0.2) ├
     ├───────────┤├─────────┤├─────────┤
q_3: ┤ Rz(-0.23) ├┤ Ry(0.3) ├┤ Rz(0.2) ├
     ├───────────┤├─────────┤├─────────┤
q_4: ┤ Rz(-0.23) ├┤ Ry(0.3) ├┤ Rz(0.2) ├
     └───────────┘└─────────┘└─────────┘

In [117]:
t

tensor([[1.9049e+04+0.j],
        [1.2365e+04+0.j],
        [1.2546e+01+0.j]])

In [91]:
t=[[1.9049e+04+0.j],
        [1.2365e+04+0.j],
        [1.2546e+01+0.j]]

In [95]:
b= np.zeros((3,4))

In [96]:
t+b

array([[1.90490000e+04+0.j, 1.90490000e+04+0.j, 1.90490000e+04+0.j,
        1.90490000e+04+0.j],
       [1.23650000e+04+0.j, 1.23650000e+04+0.j, 1.23650000e+04+0.j,
        1.23650000e+04+0.j],
       [1.25459995e+01+0.j, 1.25459995e+01+0.j, 1.25459995e+01+0.j,
        1.25459995e+01+0.j]])

In [67]:
np.random.random(3*4).shape

(12,)

In [3]:
para.shape[0]

3

In [14]:
from qiskit.opflow import I,X,Y,Z

a = (I^Z)+(X^Y)
print(a)

1.0 * IZ
+ 1.0 * XY


In [42]:
def obse_term(n_qubit, idx, typ):
    op = I
    if typ == 1:
        op = X
    elif typ == 2:
        op = Y
    elif typ == 3:
        op = Z
    ret = I
    
    for i in range(idx-1):
        ret = ret^I
    ret = ret^op
    for i in range(n_qubit-idx):
        ret = ret^I

    return 0.1*ret

In [43]:
obse_term(5,1,1)

TypeError: ListOp expecting objects of type OperatorBase, got tensor([[-1.0632],
        [-0.1325],
        [-1.0873],
        [-0.3375],
        [-1.5933],
        [ 0.1487],
        [ 0.0802],
        [ 0.3893],
        [-1.4519],
        [-0.1113],
        [-1.3306],
        [ 0.0452],
        [ 1.1772],
        [-0.9517],
        [-0.4889],
        [ 0.9313],
        [-1.8404],
        [-0.3494],
        [-1.0349],
        [ 0.8491],
        [ 0.5632],
        [ 0.1069],
        [ 1.7319],
        [-0.7073],
        [-0.2570],
        [ 0.2356],
        [-1.1561],
        [ 0.7830],
        [-0.8123],
        [ 3.9819],
        [-0.3706],
        [ 0.6667],
        [-0.5061],
        [-2.3843],
        [-0.6492],
        [ 0.8035],
        [ 0.6760],
        [ 1.0593],
        [ 0.4644],
        [-0.6050],
        [-0.7893],
        [ 0.9787],
        [-0.2578],
        [-0.0925],
        [ 0.0576],
        [-0.9215],
        [-0.3690],
        [-0.1237],
        [-1.8863],
        [ 1.9841],
        [-0.3370],
        [-0.2704],
        [ 0.3447],
        [-0.0251],
        [-0.2060],
        [ 0.8895],
        [ 0.8894],
        [-0.4283],
        [-0.1905],
        [ 0.6588],
        [ 0.4020],
        [ 0.2028],
        [-0.2151],
        [-0.0351],
        [ 2.1895],
        [ 0.3861],
        [-1.3320],
        [ 0.5717],
        [ 2.1532],
        [-1.0302],
        [ 2.1732],
        [ 0.9812],
        [-1.3283],
        [-0.2630],
        [ 0.4189],
        [-1.9842],
        [ 1.1397],
        [-0.4855],
        [-1.0943],
        [ 0.8781],
        [ 0.2532],
        [ 0.0102],
        [ 1.3152],
        [ 0.5950],
        [-2.6090],
        [ 1.9501],
        [-0.6954],
        [ 1.5803],
        [-0.4227],
        [-0.6619],
        [ 1.1841],
        [ 0.6000],
        [-0.7969],
        [-1.0811],
        [-0.3907],
        [ 0.8414],
        [ 0.7746],
        [ 1.0806],
        [-2.7393],
        [ 1.6660]])

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable

A = 2.4785692
b = 7.3256987
error = 0.1
N = 100 # number of data points

# Data
X = Variable(torch.randn(N, 1))

# (noisy) Target values that we want to learn.
t = A * X + b + Variable(torch.randn(N, 1) * error)

# Creating a model, making the optimizer, defining loss
model = nn.Linear(1, 1)
optimizer = optim.Adam(model.parameters(), lr=0.05)
loss_fn = nn.MSELoss()

# Run training
niter = 10
for _ in range(0, niter):
    optimizer.zero_grad()
    predictions = model(X)
    loss = loss_fn(predictions, t)
    loss.backward()
    print(optimizer.step())
    print()

    print("-" * 10)
    print("learned A = {}".format(list(model.parameters())[0].data[0, 0]))
    print("learned b = {}".format(list(model.parameters())[1].data[0]))

None
----------
learned A = -0.06864257156848907
learned b = 0.9035919308662415
None
----------
learned A = -0.018669694662094116
learned b = 0.9535813927650452
None
----------
learned A = 0.03125731647014618
learned b = 1.0035531520843506
None
----------
learned A = 0.08111926913261414
learned b = 1.0535000562667847
None
----------
learned A = 0.13089653849601746
learned b = 1.1034150123596191
None
----------
learned A = 0.1805691123008728
learned b = 1.1532907485961914
None
----------
learned A = 0.23011666536331177
learned b = 1.2031199932098389
None
----------
learned A = 0.2795185446739197
learned b = 1.252895712852478
None
----------
learned A = 0.32875388860702515
learned b = 1.3026106357574463
None
----------
learned A = 0.3778015971183777
learned b = 1.3522577285766602


In [31]:
n_qubit=5
init_params=np.random.random(requires_grad=True)

TypeError: random() got an unexpected keyword argument 'requires_grad'

In [56]:
def obs_term(n_qubit, idx, typ):
    op = I
    if typ == 1:
        op = X
    elif typ == 2:
        op = Y
    elif typ == 3:
        op = Z
    if idx != 0:
        ret = I
    else:
        ret = op
    for i in range(idx-1):
        ret = ret^I
    if idx != 0:
        ret = ret^op
    for i in range(n_qubit-idx-1):
        ret = ret^I
    
    return ret


In [57]:
obs_term(5,0,0)

PauliOp(Pauli('IIIII'), coeff=1.0)

In [44]:
from qiskit.opflow import (StateFn, Zero, One, Plus, Minus, H, I, X, Y, Z,
                           DictStateFn, VectorStateFn, CircuitStateFn, OperatorStateFn)

In [55]:
PauliOp(Pauli(''),coeff=1.0)

NameError: name 'PauliOp' is not defined

In [186]:
import torch
import pennylane as qml

dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev, interface='torch')
def circuit4(phi, theta):
    qml.RX(phi[0], wires=0)
    qml.RZ(phi[1], wires=1)
    qml.CNOT(wires=[0, 1])
    qml.RX(theta, wires=0)
    return qml.expval(qml.PauliZ(0))

def cost(phi, theta):
    return torch.abs(circuit4(phi, theta) - 0.5)**2

phi = torch.tensor([0.011, 0.012], requires_grad=True)
theta = torch.tensor(0.05, requires_grad=True)

opt = torch.optim.Adam([phi, theta], lr = 0.1)

steps = 200

def closure():
    opt.zero_grad()
    loss = cost(phi, theta)
    loss.backward()
    return loss

for i in range(steps):
    opt.step(closure)

In [180]:
init_params=torch.rand(n_qubit*4, requires_grad = True)

In [182]:
init_params[1].requires_grad

True

In [185]:
torch.abs(torch.tensor(4))**2

tensor(16)