In [2]:
import sys
import pennylane as qml
from pennylane import numpy as np
import pennylane.optimize as optimize

In [1]:
f=open('2.in','r')

In [3]:

inputs=f.read().split(",")

In [4]:
thetas = np.array(inputs, dtype=float)

In [5]:
thetas

tensor([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
        3.14159265, 3.14159265, 3.14159265], requires_grad=True)

In [27]:
a=np.array([int(i) for i in list(bin(3))[2:]], requires_grad=False)

In [28]:
b=np.zeros(3)

In [29]:
for i in range(len(a)):
    b[-(i+1)]=a[-(i+1)]

In [30]:
b

tensor([0., 1., 1.], requires_grad=True)

In [24]:
b[-2]=a[-2]

In [37]:
thetas=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8]

In [61]:


def flipflop(j):
        binaryi=np.array([int(i) for i in list(bin(j))[2:]], requires_grad=False)
        binaryn=np.zeros(3)
        for i in range(len(binaryi)):
            binaryn[-(i+1)]=binaryi[-(i+1)]
        for i in range(3):
            if binaryn[i]==0:
                qml.PauliX(wires=i)
        U=np.array([[np.cos(thetas[j]/2),-np.sin(thetas[j]/2)]
                    ,[np.sin(thetas[j]/2), np.cos(thetas[j]/2)]])
        qml.ControlledQubitUnitary(U, control_wires=[0, 1, 2], wires=3)
        for i in range(3):
            if binaryn[i]==0:
                qml.PauliX(wires=i)
        
                

dev = qml.device("default.qubit", wires=range(4))

@qml.qnode(dev)
def circuit():
    for i in range(3):
        qml.Hadamard(wires=i)
    for j in range(len(thetas)):
        flipflop(j)

    # QHACK #

    # Create your circuit: the first three qubits will refer to the index, the fourth to the RY rotation.

    # QHACK #

    return qml.state()

In [64]:
circuit()

tensor([0.35311154+0.j, 0.0176703 +0.j, 0.3517871 +0.j, 0.03529644+0.j,
        0.34958337+0.j, 0.05283436+0.j, 0.34650586+0.j, 0.07024022+0.j,
        0.34256227+0.j, 0.08747051+0.j, 0.33776245+0.j, 0.10448217+0.j,
        0.33211841+0.j, 0.12123268+0.j, 0.32564424+0.j, 0.13768018+0.j], requires_grad=True)

In [81]:
dev = qml.device("default.qubit", wires=3)
@qml.qnode(dev)
def circuit(theta):
    qml.Hadamard(wires=0)
    qml.CNOT(wires=[0,1])
    qml.PauliX(wires=1)
    qml.CRY(theta, wires=[1,2])
    qml.CNOT(wires=[2,1])
    return qml.state()

In [82]:
print(qml.draw(circuit)(0))

 0: ──H──╭C─────────────────╭┤ State 
 1: ─────╰X──X──╭C──────╭X──├┤ State 
 2: ────────────╰RY(0)──╰C──╰┤ State 



In [86]:
circuit(np.pi)

tensor([0.00000000e+00+0.j, 7.07106781e-01+0.j, 4.32978028e-17+0.j,
        0.00000000e+00+0.j, 7.07106781e-01+0.j, 0.00000000e+00+0.j,
        0.00000000e+00+0.j, 0.00000000e+00+0.j], requires_grad=True)