In [1]:
import sys
import pennylane as qml
from pennylane import numpy as np
import pennylane.optimize as optimize

In [33]:
f=open('1.in','r')

In [34]:
DATA_SIZE = 250
inputs=f.read().split(",")

In [35]:
inputs=np.array(inputs, dtype=int)

In [36]:
inputs.requires_grad=False

In [37]:
inputs=inputs.reshape(DATA_SIZE, -1)

In [38]:
inputs.shape

(250, 5)

In [39]:
ising_configs = inputs[:, :-1]
labels = inputs[:, -1]

In [57]:
np.random.randint(100,)

tensor([59, 76, 95, 21, 14, 32, 20, 54,  5, 54], requires_grad=True)

In [45]:
labels

tensor([-1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,
         1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1,
         1, -1, -1,  1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1,
        -1,  1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1,  1, -1,  1,
         1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,
         1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1, -1,  1,  1,
         1,  1,  1, -1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1,  1,  1,
        -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1, -1, -1,  1,  1,
        -1, -1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1,  1, -1,
         1,  1,  1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,
        -1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1,
         1, -1,  1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1,
        -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1, -1, -1,  1,  1,
        -1,  1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1, -1, -1, 

In [60]:
inputs[:20]

tensor([[ 0,  0,  1,  0, -1],
        [ 0,  0,  0,  0,  1],
        [ 0,  0,  1,  0, -1],
        [ 0,  0,  0,  0,  1],
        [ 0,  0,  0,  0, -1],
        [ 1,  1,  0,  1, -1],
        [ 0,  0,  1,  0, -1],
        [ 1,  0,  0,  1, -1],
        [ 0,  0,  0,  0,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  0,  1,  0, -1],
        [ 0,  1,  0,  1, -1],
        [ 1,  0,  0,  1, -1],
        [ 0,  0,  0,  0,  1],
        [ 1,  1,  1,  1,  1],
        [ 0,  0,  0,  0, -1],
        [ 0,  0,  0,  0,  1],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1],
        [ 0,  1,  0,  0, -1]], requires_grad=False)